### ISSUE TITLE
Backpack

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/unordinary-basics#112]
Chests worth of storage on your back. Can only go in back slot. File is located in textures/gui

![chest_backpack](https://user-images.githubusercontent.com/103650147/209555500-891e82f8-e6c2-4eb3-8548-2ea41b5e4110.png)
![barrel_backpack](https://user-images.githubusercontent.com/103650147/209555502-16813c50-d583-4523-9f74-de113a3ae427.png)

Should look like this when equipped
![image](https://user-images.githubusercontent.com/103650147/211941118-bffdff8e-990e-4731-916f-a11e6f2bf6fe.png)

**Comment by nexonerr** [comment]
Added with #167. Is currently feature complete except for rendering, which should instead be addressed by #70
