### ISSUE TITLE
[Feature Request]: Vein Miner Changes

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/unordinary-basics#123]
### Suggestion

![2022-11-12_15 22 08](https://user-images.githubusercontent.com/103650147/201481489-36ac4d52-00a1-485a-9202-12bdb73b995e.png)

To begin with, I would like the radius to be more of a sphere which goes out instead of a weird shape

Next is that Fortune does not work with this enchantment

**Comment by nexonerr** [comment]
Closed with #146
