### ISSUE TITLE
[Feature Request]: Redstone Pouch

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/unordinary-basics#131]
### Suggestion

X = Pouch
R = Redstone Dust

RRR
RXR
RRR

- [x] Item Added
- [x] Craftable
- [x] In Inventory, placing the 'Redstone Pouch' on some redstone dust (and redstone dust onto redstone pouch) will put the redstone dust into the pouch
- [x] Picking up Redstone Dust or Shift Clicking Redstone Dust into the players inventory will automatically put the Redstone Dust into the pouch
- [x] Hovering over the item in the inventory will say how much redstone dust is in the pouch
- [x] Right clicking while looking at a block will try to put redstone dust on it
- [x] Shift + Right Click will throw out a piece of redstone dust
- [x] Control + Right Click will throw out a stack of redstone dust
- [ ] JEI integration. When pressing [+] to add ingredients to bench, will take out any needed redstone from the bag.

Texture:
![redstone_pouch](https://user-images.githubusercontent.com/103650147/208945550-dd02a2f9-e778-487d-8fff-c9b384239d4b.png)

**Comment by nexonerr** [comment]
-> Item's now complete except for the last task, couldn't find a way of doing it :(
