### ISSUE TITLE
[Feature Request]: Builders Glove

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/unordinary-basics#134]
### Suggestion

Right Clicking on the item in your inventory will open up a GUI where you put in blocks

With the Builders Glove in hand, you will randomly place the blocks in the glove. As an added feature, it will replenish any blocks in the glove from blocks in your inventory.

However, when there is a block in your off-hand and you have the Builders Glove in your main hand, when aiming at another block, when right clicking, you will swap that block with the one in your off hand. Dropping the swapped block.

Item Texture: 
![builders_glove](https://user-images.githubusercontent.com/103650147/209435138-4632ce62-8a5d-4037-9bd9-fa96f045ea73.png)

Model: Ill pin in #Asset-Storage

Model Texture: 
![builders_glove_mt](https://user-images.githubusercontent.com/103650147/209435156-72f13eae-da41-4bba-8acd-4fdf574741de.png)

GUI: 
![builders_glove](https://user-images.githubusercontent.com/103650147/209348363-bd01940f-dc62-48bf-b03a-331eca66482d.png)

**Comment by nexonerr** [comment]
Feature complete implementation added, just needs some model work done, and features which are TBD
