### ISSUE TITLE
[Bug]: Checker texture (pink/black blocks) on all UB items in 190 Mods Modpack

### ISSUE THREAD

**Issue by xFirefalconx** [ManasMods/unordinary-basics#175]
### Minecraft Version

1.18.2

### ManasCore Version

1.0.2.0

### Unordinary Basics Version

1.0.1.3

### Steps to Reproduce the Bug

The exact reason is currently to be found. In my 190 Mods modpack, I added your mod recently. 
I will do a large debugging session soon and narrow down two issues, then I can tell you which mod(s) is/are linked to this. There are things in the console log though so maybe you find something concerning the issue from the latest log. 

### Expected Behavior

Items look like items, placed and in the inventory

### Actual Behavior

In my 190 Mods modpack, I added your mod recently. The textures don't show, neither in inventory, nor placed down. Hitboxes are working but for the stairs for example I just see the pink squares. 
![grafik](https://user-images.githubusercontent.com/106652912/220822485-59f5a663-a214-41b0-8046-202c6beb3a93.png)
![grafik](https://user-images.githubusercontent.com/106652912/220822623-78eab790-8a16-4144-ad49-14a8ca55647b.png)

### Extra Notes (Optional)

I actually have two latest.logs this one is from earlier but because the startup got cut off I put it here:
https://gist.github.com/xFirefalconx/f7ac11bcbf6a6950e4bc018a087c2779

### latest.log

https://gist.github.com/xFirefalconx/1e9aed31b98a483909110ccfd81c4223

**Comment by nexonerr** [comment]
Could you please try to run the mod standalone and see if it works?

**Comment by xFirefalconx** [comment]
![grafik](https://user-images.githubusercontent.com/106652912/220997250-280a3818-3bf5-4375-ab9b-f5326062b135.png)
Not working on vanilla modding.

**Comment by Contrabass26** [comment]
So UB is the only mod?

**Comment by xFirefalconx** [comment]
Exactly. And its library, of course.

**Comment by Contrabass26** [comment]
We've figured out the issue - fixed version will be up shortly

**Comment by nexonerr** [comment]
For now, just use 1.0.1.2, if you'd like, it should be working correctly

**Comment by xFirefalconx** [comment]
Okay thank you. Hopefully curseforge will show the available updates correctly. I had bugs with that lately.

**Comment by nexonerr** [comment]
The problem has been fixed, fixed version is currently processing. Closing
