### ISSUE TITLE
[Feature Request]: Add Ukrainian language to Crowdin

### ISSUE THREAD

**Issue by unroman** [ManasMods/unordinary-basics#225]
### Suggestion

Heyo! I noticed your mod and want to translate it into Ukrainian and Czech, but only Czech is available. So please add the option to translate mod into Ukrainian

**Comment by unroman** [comment]
![image](https://github.com/ManasMods/unordinary-basics/assets/75941881/472bca47-7f38-4058-8499-2f6f7f4ae9a9)
oh, as I understand it, the mod already had Ukrainian, but you deleted it, ok nvm

**Comment by Nieadni** [comment]
I can add Ukrainian. The issue was just that we didnt have any translators for it and its % was getting quite low so we removed it. Ill add Ukrainian and also Russian to the Crowdin

**Comment by Nieadni** [comment]
@unroman They have been added. Feel free to translate! https://crowdin.com/project/unordinary-basics

**Comment by unroman** [comment]
Okay, thank you. I will try to support the translation as long as I can
