### ISSUE TITLE
HoeHarvest is incompatible with Croptopia tree crops

### ISSUE THREAD

**Issue by ExcessiveAmountsOfZombies** [ManasMods/unordinary-basics#69]
https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/385

https://github.com/ManasMods/unordinary-basics/blob/master/src/main/java/com/github/manasmods/unordinary_basics/handler/HoeHandler.java#L32

as you already know the block you're dealing with is a CropBlock, it could be good to change
`blockState.getValue(CropBlock.AGE)` to `blockState.getValue(plant.getAgeProperty())`

**Comment by Nieadni** [comment]
fixed :)

Finally had time to do stuff so I fixed it
