### ISSUE TITLE
More Slots

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/unordinary-basics#70]
![pixil-frame-0 (18)](https://user-images.githubusercontent.com/103650147/212182170-fbcbe6a5-c159-48d6-8d75-79d432ed90c0.png)

Notes:
¬ For the Back and Waist Slots, please make a tag for them so other mod creators can add gear to them. See the planned items below.
¬ Could we also add some compatibility with Curios. It would appear as normal however when there is a backpack equipped, it would go on the left of that. It may look weird however I would like it if the UB inventory will be main inventory people use.
¬ The textures for the GUI's should be in the mod already, they would just need added.

----
Related Issues

- [x] #112 
- [x] #40 
- [x] #113 

New tags for stuff to go into Back and Waist Slot. 

Everything for Back Slot in UB;
- Backpack
- Quiver
- Elytra

Everything for Waist Slot in UB;
- Potion Belt
- Lantern (for Optifine / Shaders)
- Soul Lantern (for Optifine / Shaders)

**Comment by nexonerr** [comment]
Re-openning issue, as this system still needs a way of rendering worn items.

**Comment by nexonerr** [comment]
Addresed by #170, and worn items by #171
