### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ErasedTruth** [ManasMods/unordinary-basics#94]
### Minecraft Version

1.18.2

### ManasCore Version

0.0.0.17

### Unordinary Basics Version

1.0.0.8

### Steps to Reproduce the Bug

Interact with the fletching table

### Expected Behavior

Opening the gui

### Actual Behavior

doesn't do anything

### Extra Notes (Optional)

The same thing happen for the jukebox

### latest.log

https://gist.github.com/ErasedTruth/9d06f1732cac22c6003a0df53f2dd0a8

**Comment by Charismara** [comment]
Please provide the **full** latest log file

**Comment by maltesermailo** [comment]
I already fixed that bug
